### ISSUE TITLE
Unable to run sample code

### ISSUE THREAD

**Issue by darkworks** [gilmaimon/TinyWebsockets#20]
i cloned the lib in my arduino libraries folders  like

`git clone https://github.com/gilmaimon/TinyWebsockets.git`

now when i tried to upload sample code am getting error

`tiny_websockets/client.hpp: No such file or directory`

possibly due to bad structure of library folder

**Comment by gilmaimon** [comment]
Hi @darkworks,
Thanks for trying out the library!

I'm afraid you want to look at [ArduinoWebsockets](https://github.com/gilmaimon/ArduinoWebsockets) which is the Arduino version for this library :)

Let me know that everything is working for you.
Gil.

**Comment by darkworks** [comment]
Ya i tried but its slow. The message pull is slow not smooth.

**Comment by gilmaimon** [comment]
What do you mean?
Define slow. What code are you using? What hardware? Which server implementation?

You can't just throw sayings like that without explaining yourself.

**Comment by darkworks** [comment]
thanks i tried it its working good :) . can you tell how can i prevent nodemcu from getting into sleep , is there way to define interval with lib so that it can send ping to server so that nodemcu / esp not go in sleep

**Comment by darkworks** [comment]
> What do you mean?
> Define slow. What code are you using? What hardware? Which server implementation?
> 
> You can't just throw sayings like that without explaining yourself.

sorry it was sleep issue if server not send data for some time node mcu go into sleep
